from python:3-slim

run apt-get update \
  && apt-get install -y gcc geoip-database \
  && rm -rf /var/lib/apt/lists/*

run mkdir /app
workdir /app

copy req*.txt ./
run pip install --no-cache-dir -r requirements.txt -r requirements-test.txt

copy setup.py .
copy aluigi aluigi
run ./setup.py install && rm -fr build

copy . .

volume /app/volume

expose 27900/udp 28900

## trying to use non-root user:
# run chown -R nobody .
# user nobody
## unfortunately volume still belongs to root then and thus db.sqlite is read-only
