"""Server.waiting_for_sync

Revision ID: f42db407f5ce
Revises: 435e7055a710
Create Date: 2018-01-28 23:01:00.546921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f42db407f5ce'
down_revision = '435e7055a710'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('waiting_for_sync', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server', 'waiting_for_sync')
    # ### end Alembic commands ###
